"""fix-table-indexing

Revision ID: 41ad3d82818b
Revises: 8f79aa1623bc
Create Date: 2026-02-22 12:42:50.803335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41ad3d82818b'
down_revision: Union[str, Sequence[str], None] = '8f79aa1623bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_urls_original_url'), table_name='urls')
    op.create_index(op.f('ix_urls_short_code'), 'urls', ['short_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_urls_short_code'), table_name='urls')
    op.create_index(op.f('ix_urls_original_url'), 'urls', ['original_url'], unique=False)
    # ### end Alembic commands ###
