"""create_urls_table

Revision ID: 8f79aa1623bc
Revises: 
Create Date: 2026-02-22 11:54:05.524171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f79aa1623bc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('urls',
    sa.Column('short_code', sa.String(length=10), nullable=False),
    sa.Column('original_url', sa.String(), nullable=False),
    sa.Column('fetch_count', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('short_code')
    )
    op.create_index(op.f('ix_urls_original_url'), 'urls', ['original_url'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_urls_original_url'), table_name='urls')
    op.drop_table('urls')
    # ### end Alembic commands ###
