"""fix-table-indexing

Revision ID: affa2455cc19
Revises: f56b68d455a3
Create Date: 2026-03-01 12:16:07.429207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'affa2455cc19'
down_revision: Union[str, Sequence[str], None] = 'f56b68d455a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_urls_original_url'), 'urls', ['original_url'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_urls_original_url'), table_name='urls')
    # ### end Alembic commands ###
